spring:

  datasource:
    url: jdbc:h2:~/base;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    generate_ddl: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-create
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database: H2
      show_sql: true
      format_sql: true
  thymeleaf:
    cache: false

  pidfile: shared/tmp/pids/application.pid
server:
  port: 10001

logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'

turbine:
  aggregator:
    clusterConfig: JAVA-SERVICE
  appConfig: java-service


eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://peer1:8761}/eureka/

  instance:
    hostname: localhost
    nonSecurePort: 10001